"""Compare rubrics generated by SFT and RL models on the same HealthBench questions."""
import json
import torch
from src.models.grm import RubricGenerator

SEP = "=" * 80

# Load 3 diverse sample questions from healthbench benchmark split
questions = []
with open("data/healthbench_splits/benchmark_meta_eval.jsonl") as f:
    seen = set()
    for line in f:
        row = json.loads(line)
        pid = row.get("prompt_id")
        if pid in seen:
            continue
        seen.add(pid)
        prompt = row["prompt"]
        if isinstance(prompt, list):
            parts = []
            for m in prompt:
                if isinstance(m, dict):
                    c = (m.get("content") or "").strip()
                    if c:
                        parts.append(c)
            prompt_text = "\n".join(parts)
        else:
            prompt_text = str(prompt)
        questions.append(prompt_text)
        if len(questions) >= 3:
            break

print(SEP)
print("SAMPLE QUESTIONS:")
for i, q in enumerate(questions):
    print(f"\n--- Q{i+1} ({len(q)} chars) ---")
    print(q[:400] + ("..." if len(q) > 400 else ""))

# Generate rubrics from SFT model
print("\n" + SEP)
print("LOADING SFT MODEL (LoRA a16)...")
sft_grm = RubricGenerator("out/sft_lora_a16/huggingface", device="cuda:0")
sft_rubrics = []
for i, q in enumerate(questions):
    r = sft_grm.generate_rubric(q)
    sft_rubrics.append(r)
    header = f" SFT Q{i+1} "
    print(f"\n{'=' * 40}{header}{'=' * 40}")
    print(r[:2000])

del sft_grm
torch.cuda.empty_cache()

# Generate rubrics from RL model
print("\n" + SEP)
print("LOADING RL MODEL (step 300)...")
rl_grm = RubricGenerator("out/rl/global_step_300/actor/huggingface", device="cuda:0")
rl_rubrics = []
for i, q in enumerate(questions):
    r = rl_grm.generate_rubric(q)
    rl_rubrics.append(r)
    header = f" RL Q{i+1} "
    print(f"\n{'=' * 40}{header}{'=' * 40}")
    print(r[:2000])

del rl_grm
torch.cuda.empty_cache()

with open("out/bench/rubric_comparison.json", "w") as f:
    json.dump(
        [
            {"question": q[:200], "sft_rubric": s, "rl_rubric": r}
            for q, s, r in zip(questions, sft_rubrics, rl_rubrics)
        ],
        f,
        indent=2,
        ensure_ascii=False,
    )
print("\nSaved to out/bench/rubric_comparison.json")
